name: Auto Domain Scraper

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: scraper
        run: npm install

      - name: Run Scraper
        working-directory: scraper
        run: node scrape.js

      - name: Commit & Push Updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add public/domains.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto update domains.json [skip ci]"
            git push
          fi
